name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn -f back/pom.xml clean install

    - name: Generate Surefire Test Reports
      run: mvn -f back/pom.xml surefire-report:report

    - name: Test Report
      uses: phoenix-actions/test-reporting@v8
      id: test-report
      if: always()  # Exécuter cette étape même si les étapes précédentes échouent
      with:
        name: Maven Surefire Tests
        path: back/target/site/surefire-report  # Choisir le chemin approprié selon votre configuration
        reporter: junit
