name: Java CI

on:
    # Trigger the workflow on push for the main branch
    # and pull request for main and card-* prefix branches
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            # Push events to branches matching refs/heads/card-*
            - 'card-/**'
jobs:
    build_Java:
        runs-on: windows-latest
        defaults:
            run:
                working-directory: back 
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 1.11
              uses: actions/setup-java@v4
              with:
                  java-version: 11
                  distribution: 'temurin'
                  cache: 'maven'

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '16'
                  
            - name: Build and Test with Maven
              run: mvn -B clean package --file pom.xml

            - uses: actions/upload-artifact@v4
              with:
                name: back_coverage
                path: back/target/site
        
            - name: Cache SonarQube packages
              uses: actions/cache@v1
              with:
                  path: ~/.sonar/cache
                  key: ${{ runner.os }}-sonar
                  restore-keys: ${{ runner.os }}-sonar
            - name: Cache Maven packages
              uses: actions/cache@v1
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2
            - name: Build and analyze
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
              run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=CI-CD -Dsonar.projectName='CI/CD'
              
    build_Angular:
        runs-on: windows-latest
        defaults:
          run:
            working-directory: front
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
    
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '16'
    
        - name: Install dependencies
          run:  npm install
    
        - name: Run tests and generate coverage report
          run:  npm run test_CI
                     
        - uses: actions/upload-artifact@v4
          with:
            name: front_coverage
            path: front/coverage



